---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-webapp-deployment
spec:
  selector:
    matchLabels:
      app: python-webapp-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: python-webapp-k8s
    spec:
      containers:
        - name: python-webapp-k8s
          image: adijaiswal/santa:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 1Gi
              cpu: 1000m
            limits:
              memory: 1Gi
              cpu: 1000m

---
apiVersion: v1
kind: Service
metadata:
  name: python-webapp-k8-svc
spec:
  selector:
    app: python-webapp-k8s
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
